### ISSUE TITLE
[Milestone] Clean up code

### ISSUE THREAD

**Issue by RobotsOnDrugs** [RobotsOnDrugs/LibMai#9]
### Work to do

- Eliminate warnings
- Refactor as needed to simplify overly complex methods
- Simplify the flow of building character records and make it easy to follow as much as possible
- Reorganize files/namespaces as needed to make it easy to find a specific set of APIs

**Comment by RobotsOnDrugs** [comment]
- [ ] Move math converters to FakeUnity
- [ ] Move AI character constants out of card constants file
- [ ] Move the PNG empty array to a better place
- [ ] Get rid of interfaces
- [ ] Revisit character constant meanings
